apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - merge:
              mergeKeys: 
                - "name"
              generators:
                - git:
                    repoURL: https://github.com/bahmanzadeh/argovault.git
                    revision: main
                    files:
                    - path: ./cluster-tenancy-map.json
                - clusters: {} # cluster that is locally configured on Argocd
            selector:
              matchExpressions:
                - key: server
                  operator: Exists
          - list:
              elementsYaml: "{{ .namespaces | toYaml }}"
  template:
    metadata:
      name: 'infra-{{ .name }}-{{ .namespace }}'
    spec:
      destination:
        name: '{{ .name }}'
        namespace: '{{ .namespace }}'
      project: default
      source:
        # Helm Chart details
        repoURL: https://github.com/bahmanzadeh/argovault.git
        targetRevision: HEAD
        path: mychart1
        plugin:
          name: argocd-vault-plugin-helm
          env:
            - name: HELM_ARGS
              value: -f "values.yaml" -f "../values/dev/{{ .name }}/{{ .namespace }}/values.yaml"
            # - name: VAULT_NAMESPACE
            #   value: 

          # could be "infra-{{ .namespace }}"
          # releaseName: "infra-services"
          # ignoreMissingValueFiles: false
          # valueFiles:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true