kind: Secret
apiVersion: v1
metadata:
  name: vault-configuration
  namespace: argocd
type: Opaque
stringData:
  VAULT_ADDR: http://vault.vault:8200
  VAULT_TOKEN: hvs.CAESIIG6hXN9__SYN8xmmN8ep5686I3mXNmfpM6aZdapZuDCGh4KHGh2cy5JVURwdmtrSmFCRHBrUVIxVUt2S0NWTlY
  AVP_TYPE: vault
  AVP_AUTH_TYPE: token
