kind: Secret
apiVersion: v1
metadata:
  name: secret-chart-inlinepath
type: Opaque
data:
  user: <path:kv/data/application#user | base64encode>
  password: <path:kv/data/application#password | base64encode>
  
  #{{ .Values.kafka.user | b64enc }}
  #{{ .Values.kafka.password | b64enc }}