kind: Secret
apiVersion: v1
metadata:
  name: secret-nochart-inline
type: Opaque
data:
  user: <path:kv/data/application#user | base64encode>
  password: <path:kv/data/application#password | base64encode>